import java.nio.charset.StandardCharsets

apply plugin: "com.android.application"
apply plugin: "kotlin-android"

def verName = APP_VERSION_NAME
def verCode = 11529

def gitHashProc = new ProcessBuilder("git", "log", "--pretty=format:'%h'", "-n", "1").redirectErrorStream(true).start()
def gitHashBuf = new byte[16]
gitHashProc.getInputStream().read(gitHashBuf)
def gitHash = new String(gitHashBuf, StandardCharsets.UTF_8).trim().replace('\'','')

verName += "-" + gitHash
println(gitHash)

def archs = List.of("arm64-v8a", "armeabi-v7a", "x86", "x86_64")

def officialVer = APP_VERSION_NAME
def officialCode = APP_VERSION_CODE

def serviceAccountCredentialsFile = rootProject.file("service_account_credentials.json")

def beta = verName.contains("preview")

if (serviceAccountCredentialsFile.isFile()) {
    setupPlay(beta)
    play.serviceAccountCredentials = serviceAccountCredentialsFile
} else if (System.getenv().containsKey("ANDROID_PUBLISHER_CREDENTIALS")) {
    setupPlay(beta)
}

void setupPlay(boolean beta) {
    apply plugin: "com.github.triplet.play"
    play {
        track = beta ? "beta" : "production"
        defaultToAppBundles = true
    }
}

apply plugin: 'org.telegram.lottie-meta'
apply plugin: 'idea'

idea {
    module {
        excludeDirs += [
            file('jni/third_party'),
            file('jni/ffmpeg'),
            file('jni/tlottie'),
            file('jni/boringssl'),
            file('jni/sqlite')
        ]
    }
}

repositories {
    mavenCentral()
    google()
    maven {
        url = 'https://www.jitpack.io'
        content {
            includeModule 'com.github.UnifiedPush', 'android-connector'
        }
    }
}

configurations {
    compile.exclude module: "support-v4"
}

def keystorePath = null
def keystorePwd = null
def alias = null
def pwd = null
def disableCMakeRelWithDebInfo = System.getenv("COMPILE_NATIVE") == null

Properties properties
def base64 = System.getenv("LOCAL_PROPERTIES")
if (base64 != null && !base64.isBlank()) {
    properties = new Properties()
    properties.load(new ByteArrayInputStream(Base64.decoder.decode(base64)))
} else if (project.rootProject.file("local.properties").exists()) {
    properties = new Properties()
    properties.load(project.rootProject.file("local.properties").newDataInputStream())
}

if (properties != null) {
    keystorePath = properties.getProperty("KEYSTORE_PATH")
    keystorePwd = properties.getProperty("KEYSTORE_PASS")
    alias = properties.getProperty("ALIAS_NAME")
    pwd = properties.getProperty("ALIAS_PASS")
}

keystorePath = keystorePath ?: System.getenv("KEYSTORE_PATH")
keystorePwd = keystorePwd ?: System.getenv("KEYSTORE_PASS")
alias = alias ?: System.getenv("ALIAS_NAME")
pwd = pwd ?: System.getenv("ALIAS_PASS")
def keystore = keystorePath ? rootProject.file(keystorePath) : project.file("release.keystore")
System.out.println("using keystore: " + keystore.path)

def targetTask = ""
if (!gradle.startParameter.taskNames.isEmpty()) {
    if (gradle.startParameter.taskNames.size == 1) {
        targetTask = gradle.startParameter.taskNames[0].toLowerCase()
    }
}

def nativeTarget = System.getenv("NATIVE_TARGET")
if (nativeTarget == null) nativeTarget = ""

android {

    buildFeatures.aidl = true
    buildFeatures.buildConfig = true

    defaultConfig.applicationId = APP_PACKAGE


    splits {

        abi {
            if (nativeTarget.isBlank()) {
                enable = true
                reset()
                include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                universalApk = false
            } else if (nativeTarget.toLowerCase().equals("universal")) {
                enable = false
                universalApk = true
            } else if (!archs.contains(nativeTarget.toLowerCase())) {
                enable = false
                universalApk = false
            }
        }

    }

    defaultConfig {
        minSdkVersion 21
        //noinspection ExpiredTargetSdkVersion,OldTargetApi
        targetSdkVersion 34

        versionName verName
        versionCode verCode

        def appId = "1391584"
        def appHash = "355c91550b0d658cfb7ff89dcf91a08c"
        def mySalt = "030?"

        //obtain your own keys at https://core.telegram.org/api/obtaining_api_id

        if (properties != null) {
            appId = properties.getProperty("TELEGRAM_APP_ID") ?: System.getenv("TELEGRAM_APP_ID") ?: appId
            appHash = properties.getProperty("TELEGRAM_APP_HASH") ?: System.getenv("TELEGRAM_APP_HASH") ?: appHash
            mySalt = properties.getProperty("SALT_030") ?: System.getenv("SALT_030") ?: mySalt
        } else if (System.getenv("TELEGRAM_APP_ID") != null) {
            appId = System.getenv("TELEGRAM_APP_ID") ?: appId
            appHash = System.getenv("TELEGRAM_APP_HASH") ?: appHash
        }
        // System.out.printf("api_id=%s", appId)


        buildConfigField "String", "OFFICIAL_VERSION", "\"" + officialVer + "\""
        buildConfigField "int", "OFFICIAL_VERSION_CODE", officialCode + ""
        buildConfigField "int", "APP_ID", appId
        buildConfigField "String", "APP_HASH", "\"" + appHash + "\""
        buildConfigField "boolean", "BUNDLE", "false"
        buildConfigField "int", "VERSION_NUM", "6"
        buildConfigField "String", "SALT_030", "\"" + mySalt + "\""
        resValue "string", "package_name", APP_PACKAGE

//        ndk {
//            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
//        }

        externalNativeBuild {
            cmake {
                version '3.22.1'
                arguments '-DANDROID_STL=c++_static', '-DANDROID_PLATFORM=android-21' //, '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON'
                targets 'tmessages.49'
            }
        }

    }

    bundle {
        language {
            enableSplit = false
        }
    }

    externalNativeBuild {
        cmake {
            path "jni/CMakeLists.txt"
        }
    }


    dexOptions {
        jumboMode = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17

        coreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    signingConfigs {
        release {
            storeFile keystore
            storePassword keystorePwd
            keyAlias alias
            keyPassword pwd
        }
    }

    buildTypes {
        debug {
            isDefault = true
            debuggable = true
            jniDebuggable = true
            multiDexEnabled = true
            signingConfig = (keystorePwd == null ? signingConfigs.debug : signingConfigs.release)
            ndk.debugSymbolLevel = 'FULL'
        }

        release {
            debuggable = false
            jniDebuggable = false
            minifyEnabled = true
            shrinkResources = true
            multiDexEnabled = true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro", '../TMessagesProj/proguard-rules-beta.pro'
            matchingFallbacks = ["release", "debug"]
            signingConfig = (keystorePwd == null ? signingConfigs.debug : signingConfigs.release)
        }

        foss {
            debuggable false
            jniDebuggable = false
            minifyEnabled = true
            shrinkResources = true
            multiDexEnabled = true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro", '../TMessagesProj/proguard-rules-beta.pro'
            matchingFallbacks = ["release", "debug"]
        }

        fdroidRelease {
            initWith foss
            matchingFallbacks = ["release", "debug"]
        }
    }

    sourceSets {

        main {
            jni.srcDirs = []
            aidl.srcDirs = ["src/main/aidl"]
            assets.srcDirs = ["src/main/assets"]
        }

        debug {
            java {
                srcDirs "src/main/java"
            }
            jni.srcDirs = ["./jni/"]
        }

        release {
            jni.srcDirs = []
            jniLibs {
                srcDir "src/main/libs"
            }
        }

        foss {
            jni {
                srcDirs = ["./jni/"]
            }
        }

        fdroidRelease {
            jni {
                srcDirs = ["./jni/"]
            }
            jniLibs.srcDirs = []
        }

    }

    flavorDimensions ["version"]

    sourceSets.all { set ->
        if (set.name.startsWith("full")) {
            set.dependencies {
                implementation fileTree("libs")
            }
        }
    }

    tasks.all { task ->
        if (((task.name.endsWith("Ndk") || task.name.startsWith("generateJsonModel") || task.name.startsWith("externalNativeBuild"))) && !(task.name.contains("Debug") || task.name.contains("Foss") || task.name.contains("Fdroid"))) {
            task.enabled = false
        }
        if (task.name.contains("uploadCrashlyticsMappingFile")) {
            enabled = false
        }
        if (disableCMakeRelWithDebInfo && task.name.contains("CMakeRelWithDebInfo") && !targetTask.contains("fdroid")) {
            enabled = false
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = outputFileName.replace("-mini", "").replace("-release", "").replace("TMessagesProj", "Momo-v" + versionName)
        }
    }

}

def fcmVersion = "23.0.7"
def crashlyticsVersion = "18.2.12"
def playCoreVersion = "1.10.3"

dependencies {

    implementation "androidx.browser:browser:1.8.0"
    implementation "androidx.core:core-ktx:1.16.0"
    implementation 'androidx.fragment:fragment-ktx:1.7.1'
    implementation "androidx.palette:palette-ktx:1.0.0"
    implementation "androidx.viewpager:viewpager:1.1.0"
    implementation "androidx.exifinterface:exifinterface:1.4.2"
    implementation "androidx.interpolator:interpolator:1.0.0"
    implementation "androidx.dynamicanimation:dynamicanimation:1.1.0"
    implementation "androidx.multidex:multidex:2.0.1"
    implementation "androidx.sharetarget:sharetarget:1.2.0"
    implementation 'androidx.interpolator:interpolator:1.0.0'
    implementation 'androidx.biometric:biometric:1.1.0'

    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation "com.github.spotbugs:spotbugs-annotations:4.9.8"
    implementation 'com.google.zxing:core:3.5.4'

    implementation 'androidx.car.app:app:1.4.0'
    implementation 'androidx.car.app:app-projected:1.4.0'

    // just follow official
//    implementation 'com.google.android.gms:play-services-cast-framework:21.4.0'
    implementation("androidx.mediarouter:mediarouter:1.8.1") {
        exclude group: 'androidx.recyclerview'
    }
//    implementation 'org.nanohttpd:nanohttpd:2.3.1'

    compileOnly 'org.checkerframework:checker-qual:2.5.8'
    compileOnly 'org.checkerframework:checker-compat-qual:2.5.6'

    // don"t change this :)
    //noinspection GradleDependency
    implementation "com.googlecode.mp4parser:isoparser:1.1.22"

    implementation "com.google.code.gson:gson:2.13.2"
    implementation "org.maplibre.gl:android-sdk:11.13.5"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.10"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"

    implementation 'com.github.UnifiedPush:android-connector:2.3.1'
    implementation "com.squareup.okhttp3:okhttp:5.3.2"
    implementation 'com.neovisionaries:nv-websocket-client:2.14'
    implementation 'dnsjava:dnsjava:3.6.4'
    implementation "org.dizitart:nitrite:4.3.2"
    implementation 'org.dizitart:nitrite-mvstore-adapter:4.3.2'
    implementation 'org.apache.commons:commons-lang3:3.20.0'

    // for whisper
    implementation 'com.google.ai.edge.litert:litert:1.4.1'
    implementation ('com.google.ai.edge.litert:litert-support:1.4.1') {
        exclude group: "com.google.ai.edge.litert", module: "litert-api"
    }

    // ogg to samples
//    implementation 'com.soywiz.korlibs.korge:korio:4.0.0'
    implementation 'io.github.jaredmdobson:concentus:1.0.2'
    implementation "org.gagravarr:vorbis-java-core:0.8"

    implementation "com.jakewharton:process-phoenix:3.0.0"
    implementation 'com.google.guava:guava:33.5.0-android'
//    implementation 'com.airbnb.android:lottie:6.4.0' // 030: removed from upstream
//    implementation 'com.google.android.play:integrity:1.3.0'
//    implementation 'com.google.android.gms:play-services-safetynet:18.0.1'

    implementation "io.noties.markwon:core:4.6.2"
    implementation "io.noties.markwon:ext-strikethrough:4.6.2"
    implementation "io.noties.markwon:ext-tables:4.6.2"
    implementation "io.noties.markwon:html:4.6.2"
    implementation "io.noties.markwon:inline-parser:4.6.2"
    implementation("io.noties.markwon:ext-latex:4.6.2") {
        exclude group: 'ru.noties', module: 'jlatexmath-android'
    }
    api project(':TMessagesProj:lib:jlatexmath')

    compileOnly 'org.yaml:snakeyaml:2.6'
//    fullImplementation 'org.yaml:snakeyaml:2.3'

    implementation project(":openpgp-api")

    compileOnly fileTree("libs")

//    compileOnly "com.google.firebase:firebase-messaging:$fcmVersion"
//    compileOnly "com.google.firebase:firebase-crashlytics:$crashlyticsVersion"
//    compileOnly "com.google.android.play:core:$playCoreVersion"

//    debugImplementation 'com.google.android.gms:play-services-maps:18.1.0'
//    debugImplementation 'com.google.android.gms:play-services-location:20.0.0'
//    releaseImplementation 'com.google.android.gms:play-services-maps:18.1.0'
//    releaseImplementation 'com.google.android.gms:play-services-location:20.0.0'

//    debugImplementation "com.google.firebase:firebase-messaging:$fcmVersion"
//    debugImplementation "com.google.firebase:firebase-crashlytics:$crashlyticsVersion"
//    debugImplementation "com.google.android.play:core:$playCoreVersion"
//    releaseImplementation "com.google.firebase:firebase-messaging:$fcmVersion"
//    releaseImplementation "com.google.firebase:firebase-crashlytics:$crashlyticsVersion"
//    releaseImplementation "com.google.android.play:core:$playCoreVersion"

    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'

    testImplementation "junit:junit:4.13.2"
    testImplementation "androidx.test:core:1.6.1"
    testImplementation "org.robolectric:robolectric:4.5.1"

    implementation "androidx.credentials:credentials:1.6.0-alpha04"
//    implementation "androidx.credentials:credentials-play-services-auth:1.6.0-alpha04" // required for older devices but anyway

//    implementation 'com.google.mlkit:translate:17.0.3'

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.10") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.10") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
//    implementation 'com.google.android.recaptcha:recaptcha:18.7.1'

    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.5"

}

android {
    compileSdkVersion 36
    buildToolsVersion '36.0.0'
    ndkVersion = rootProject.ext.ndkVersion


    packagingOptions {
        jniLibs {
            excludes += ['/fabric/**', '/META-INF/native-image/**']
            pickFirsts += ['**/libtmessages.*.so']
        }
        resources {
            excludes += ['/fabric/**', '/META-INF/*.version', '/META-INF/*.kotlin_module', '/META-INF/native-image/**', '/builddef.lst', '/*.txt', '/DebugProbesKt.bin', '/okhttp3/internal/publicsuffix/NOTICE', '/META-INF/INDEX.LIST']
        }
    }
    lint {
        disable 'MissingTranslation', 'ExtraTranslation', 'BlockedPrivateApi', 'Instantiatable'
    }

    tasks.all { task ->
        if (task.name.startsWith("uploadCrashlyticsMappingFile")) {
            task.enabled = false
        } else if (task.name.contains("Crashlytics")) {
            task.enabled = false
        } else if (task.name.endsWith("GoogleServices")) {
            task.enabled = false
        }
    }

    lintOptions {
        disable 'MissingTranslation'
        disable 'ExtraTranslation'
        disable 'BlockedPrivateApi'
    }

    namespace = 'org.telegram.messenger'
}
